sonar.organization=sharmilirudraraju98
sonar.projectKey=SharmiliRudraraju98_fund-transfer-demo
sonar.sources=account-service,transfer-service
sonar.exclusions=**/venv/**,**/__pycache__/**,**/tests/**
sonar.python.version=3.11